### ISSUE TITLE
Appreciation post

### ISSUE THREAD

**Issue by mayurdb** [Tobiadefami/fuxion#23]
This is quite cool and very useful. Great work!

I had to change a few things around but was able to use to generate some data for me. Maybe the documentation needs a section on how to generate new data:
```
python generators.py /Users/mayurb/src/open/ai/fuxion/templates/generator/jobs.template /Users/mayurb/src/open/ai/fuxion/few_shot_examples/jobs.json
```

**Comment by Tobiadefami** [comment]
I'm glad you found it useful. 

And apologies for the outdated docs, there was a huge refactor on the project and I am working on updating the docs for proper guidance on how to use it.

**Comment by Tobiadefami** [comment]
Docs Updated.

Also, you can now install fuxion via pip with

`pip install fuxion`
